const LOAD_DATA = "LOAD_DATA";
const LOAD_DATA_FAIL = "LOAD_DATA_FAIL";
const REGISTER = "REGISTER";
const REGISTER_FAIL = "REGISTER_FAIL";
const LOGIN = "LOGIN";
const LOGIN_FAIL = "LOGIN_FAIL";

export {
  LOAD_DATA,
  LOAD_DATA_FAIL,
  REGISTER,
  REGISTER_FAIL,
  LOGIN,
  LOGIN_FAIL,
};
